name: Aecis Arkitektura
favicon: null
layout_spectrum: 0.25659
typography_spectrum: 0.68647
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#db2b27'
    - '#ffffff'
    - '#e6706d'
    - '#f6cac9'
    - '#efa2a0'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
