typography_spectrum: 0.45924
color:
  brandColors:
    - '#db2b27'
    - '#ffffff'
    - '#e6706d'
    - '#f6cac9'
    - '#efa2a0'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.1875
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.25659
analytics:
  google: null
  facebook: null
  twitter: null
name: Aecis Arkitektura
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Love the way you live
purpose: []
